version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      wasmtime-deps:
        patterns:
          - "wasmtime"
          - "wasmtime-wasi"
          - "wasi-common"
      patch:
        update-types:
        - "patch"